# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers
        environment:
          - MYSQL_PWD: root
          - MYSQL_USER: dbuser
          - MYSQL_PASSWORD: very-secret
          - SECRETKEY: very-very-secret
        
      - image: circleci/mysql:5.7.23
        environment:
          - MYSQL_ROOT_PASSWORD: root
          - MYSQL_USER: dbuser
          - MYSQL_PASSWORD: very-secret
          - SECRETKEY: very-very-secret

    working_directory: ~/SOEN343

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: sudo apt-get install -y mysql-client

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      
      - run:
          name: setup database
        # Create db and run all migrations
          command: |
            mysql -u root -h 127.0.0.1 -e "GRANT ALL PRIVILEGES ON anansi_db.* TO 'dbuser'@'%'; FLUSH PRIVILEGES"
            node_modules/db-migrate/bin/db-migrate db:create anansi_db -e creation && node_modules/db-migrate/bin/db-migrate up
        
      - run: 
          name: test
          command: npm test
      
      - run:
          name: lint
          command: npm run lint
      
      - store_artifacts: 
          path: test-report.html
          prefix: coverage
